# Generated by Django 3.1.2 on 2020-11-29 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('ngos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ngos.ngos')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
        ),
    ]
