# Generated by Django 3.1.2 on 2020-12-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='photo',
            field=models.ImageField(default='static/img/equipments/equipment.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
