# Generated by Django 3.1.2 on 2020-12-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0002_auto_20201201_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
