# Generated by Django 3.1.2 on 2020-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement', '0003_auto_20201201_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
